# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_description', models.TextField(verbose_name='Breve Descri\xe7\xe3o')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Custo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pre\xe7o')),
                ('menu', models.BooleanField(default=True, verbose_name='Menu')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
