# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180525_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/products/'),
            preserve_default=False,
        ),
    ]
