# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180615_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='restaurant.Product', verbose_name='Produto'),
        ),
    ]
