# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_orderproduct_served'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurant.Product', verbose_name='Produto'),
        ),
    ]
