# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20180621_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AddField(
            model_name='order',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
    ]
