# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20180621_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('debit', 'D\xe9bito'), ('credit', 'Cr\xe9bito')], max_length=50, null=True),
        ),
    ]
