# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('debit', 'D\xe9bito'), ('credit', 'Cr\xe9bito')], max_length=50, null=True, verbose_name='Pagamento'),
        ),
    ]
